name: Tests

on:
  push:

jobs:
  run-tests:
    name: Brownie tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Setup node.js version
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install poetry
        run: pip install --user poetry==1.1.13

      - name: Install poetry requirements
        run: poetry install

      - name: Install ganache
        run: yarn

      - name: Import network config to connect brownie with local Ganache
        run: poetry run brownie networks import network-config.yaml True

      - name: Run tests
        run: >
          poetry run
          brownie test -s --network mainnet-fork
        env:
          WEB3_INFURA_PROJECT_ID: ${{ secrets.WEB3_INFURA_PROJECT_ID }}
          ETHERSCAN_TOKEN: ${{ secrets.ETHERSCAN_TOKEN }}
